plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}

repositories { mavenCentral() }

javafx {
    version = '17.0.9'
    modules = ['javafx.controls', 'javafx.graphics', 'javafx.swing']
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'ca.prmr.JetUML.JetUML'
}

test {
    useJUnitPlatform()
}

sourceSets {
    main {
        java.srcDirs = ['src']
        resources.srcDirs = ['src']
    }
    test {
        java.srcDirs = ['test']
        resources.srcDirs = ['test']
    }
}

jacocoTestReport {
    dependsOn test
    reports { xml.required.set(true); html.required.set(true) }
}
